MOCAP_BLEND_RIG_TOKEN = "mocap"

JOINT_LABEL_MAPPING = {'Center_Head': [15],
                       'Center_Neck': [20, 32, 33, 34, 35, 36, 37, 38, 39, 40],
                       'Center_Root': [1],
                       'Center_Spine': [8, 23, 24, 25, 26, 27, 28, 29, 30, 31],
                       'Left_Collar': [18, 170],
                       'Left_Elbow': [10, 177, 185, 193, 201, 209],
                       'Left_Foot': [4],
                       'Left_Hand': [11],
                       'Left_Hip': [2, 172, 180, 188, 196, 204],
                       'Left_Index Finger': [54, 55, 56, 57],
                       'Left_Knee': [3, 173, 181, 189, 197, 205],
                       'Left_Middle Finger': [58, 59, 60, 61],
                       'Left_Pinky Finger': [66, 67, 68, 69],
                       'Left_Ring Finger': [62, 63, 64, 65],
                       'Left_Shoulder': [9, 176, 184, 192, 200, 208],
                       'Left_Thumb': [50, 51, 52, 53],
                       'Left_Toe': [16],
                       'Right_Collar': [19, 171],
                       'Right_Elbow': [13, 179, 187, 195, 203, 211],
                       'Right_Foot': [7],
                       'Right_Hand': [14],
                       'Right_Hip': [5, 174, 182, 190, 198, 206],
                       'Right_Index Finger': [78, 79, 80, 81],
                       'Right_Knee': [6, 175, 183, 191, 199, 207],
                       'Right_Middle Finger': [82, 83, 84, 85],
                       'Right_Pinky Finger': [90, 91, 92, 93],
                       'Right_Ring Finger': [86, 87, 88, 89],
                       'Right_Shoulder': [12, 178, 186, 194, 202, 210],
                       'Right_Thumb': [74, 75, 76, 77],
                       'Right_Toe': [17]}

JOINT_CONTROL_MAPPING = {"C_chest{}_JNT": ["C_chest_CTL"],
                         "C_head{}_JNT": ["C_head_CTL"],
                         "C_hip{}_JNT": ["C_cog_CTL", "C_hip_CTL"],
                         "C_neck1{}_JNT": ["C_neckBase_CTL"],
                         "L_ankle{}_JNT": ["L_legEndFk_CTL", "L_legIk_CTL"],
                         "L_ball{}_JNT": ["L_toeFk_CTL", "L_toeIk_CTL"],
                         "L_loArm{}_JNT": ["L_loArmFk_CTL"],
                         "L_loLeg{}_JNT": ["L_loLegFk_CTL"],
                         "L_shoulder{}_JNT": ["L_shoulder_CTL"],
                         "L_upArm{}_JNT": ["L_upArmFk_CTL", "L_armPv_CTL"],
                         "L_upLeg{}_JNT": ["L_upLegFk_CTL", "L_legPv_CTL"],
                         "L_wrist{}_JNT": ["L_armIk_CTL", "L_wristFk_CTL"],
                         "L_thumb2{}_JNT": ["L_thumb1_CTL"],
                         "L_thumb3{}_JNT": ["L_thumb2_CTL"],
                         "L_index2{}_JNT": ["L_index1_CTL"],
                         "L_index3{}_JNT": ["L_index2_CTL"],
                         "L_index4{}_JNT": ["L_index3_CTL"],
                         "L_middle2{}_JNT": ["L_middle1_CTL"],
                         "L_middle3{}_JNT": ["L_middle2_CTL"],
                         "L_middle4{}_JNT": ["L_middle3_CTL"],
                         "L_ring2{}_JNT": ["L_ring1_CTL"],
                         "L_ring3{}_JNT": ["L_ring2_CTL"],
                         "L_ring4{}_JNT": ["L_ring3_CTL"],
                         "L_pinky2{}_JNT": ["L_pinky1_CTL"],
                         "L_pinky3{}_JNT": ["L_pinky2_CTL"],
                         "L_pinky4{}_JNT": ["L_pinky3_CTL"],
                         "L_thumb1{}_JNT": ["L_thumbMeta_CTL"],
                         "L_index1{}_JNT": ["L_indexMeta_CTL"],
                         "L_middle1{}_JNT": ["L_middleMeta_CTL"],
                         "L_ring1{}_JNT": ["L_ringMeta_CTL"],
                         "L_pinky1{}_JNT": ["L_pinkyMeta_CTL"],
                         "R_ankle{}_JNT": ["R_legEndFk_CTL", "R_legIk_CTL"],
                         "R_ball{}_JNT": ["R_toeFk_CTL", "R_toeIk_CTL"],
                         "R_loArm{}_JNT": ["R_loArmFk_CTL"],
                         "R_loLeg{}_JNT": ["R_loLegFk_CTL"],
                         "R_shoulder{}_JNT": ["R_shoulder_CTL"],
                         "R_upArm{}_JNT": ["R_upArmFk_CTL", "R_armPv_CTL"],
                         "R_upLeg{}_JNT": ["R_upLegFk_CTL", "R_legPv_CTL"],
                         "R_wrist{}_JNT": ["R_armIk_CTL", "R_wristFk_CTL"],
                         "R_thumb2{}_JNT": ["R_thumb1_CTL"],
                         "R_thumb3{}_JNT": ["R_thumb2_CTL"],
                         "R_index2{}_JNT": ["R_index1_CTL"],
                         "R_index3{}_JNT": ["R_index2_CTL"],
                         "R_index4{}_JNT": ["R_index3_CTL"],
                         "R_middle2{}_JNT": ["R_middle1_CTL"],
                         "R_middle3{}_JNT": ["R_middle2_CTL"],
                         "R_middle4{}_JNT": ["R_middle3_CTL"],
                         "R_ring2{}_JNT": ["R_ring1_CTL"],
                         "R_ring3{}_JNT": ["R_ring2_CTL"],
                         "R_ring4{}_JNT": ["R_ring3_CTL"],
                         "R_pinky2{}_JNT": ["R_pinky1_CTL"],
                         "R_pinky3{}_JNT": ["R_pinky2_CTL"],
                         "R_pinky4{}_JNT": ["R_pinky3_CTL"],
                         "R_thumb1{}_JNT": ["R_thumbMeta_CTL"],
                         "R_index1{}_JNT": ["R_indexMeta_CTL"],
                         "R_middle1{}_JNT": ["R_middleMeta_CTL"],
                         "R_ring1{}_JNT": ["R_ringMeta_CTL"],
                         "R_pinky1{}_JNT": ["R_pinkyMeta_CTL"]
                         }
